spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_demo
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
